### ISSUE TITLE
Slower Performance After Update

### ISSUE THREAD

**Issue by dejanzelic** [Hansen8601/control4-mediaplayer#1]
Hello!

Thank you so much for the time you've creating this integration. I use it literally every day and it has a big impact in my life. 

I noticed that after a semi-recent update, the integrations started going much slower. Specifically, this commit: https://github.com/Hansen8601/control4-mediaplayer/commit/52807bdf269e68a837c855f6562cb406aebc5f3c

The old code would send a UDP packet like so:

```
def send_udp_command(command, host, port):
    COUNTER = "0s2a" + str(random.randint(10, 99))
    COMMAND = COUNTER + " " + command + " \r\n"

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(1)
    sock.setblocking(0)
    sock.sendto( bytes(COMMAND, "utf-8"), (host, port))

    ready = select.select([sock], [], [], 1)
    if ready[0]:
        received = str(sock.recv(1024), "utf-8")
        sock.close()

    return received
```
Specifically `sock.setblocking(0)` made it so we're not waiting for the request to be sent. The new code is:

```
def send_udp_command(command, host, port):
    COUNTER = "0s2a" + str(random.randint(10, 99))
    COMMAND = COUNTER + " " + command + " \r\n"

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(1)
    sock.setblocking(0)
    sock.sendto( bytes(COMMAND, "utf-8"), (host, port))

    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(1)
        sock.sendto(bytes(COMMAND, "utf-8"), (host, port))
        data, _ = sock.recvfrom(1024)
        received = str(data, "utf-8")
    except socket.timeout:
        received = "Timeout occurred during data reception"
    except Exception as e:
        received = f{e}
    finally:
        sock.close()

    return received
```

First, it looks like we're sending the request twice? Once in a try...except block and once outside of it. And then in the try...except block we don't disable blocking.

By changing it to the old method, I was able to have much better performance. 

I could and am willing to make a pull request to clean this up. But I assume you intentionally made this change and I wanted to better understand the problem this fixed before I blindly make a change.

**Comment by Hansen8601** [comment]
Thanks for pointing out the duplicate send. I fixed this on github. In my
live copy I had the first one commented out, so I never noticed it.
